parameters:
#    leng_ocr_api.example.class: Leng\Bundle\OcrApiBundle\Example

services:
#    leng_ocr_api.example:
#        class: %leng_ocr_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
